CREATE TABLE _users (
        id bigint generated by default as identity,
        email varchar(255) not null,
        password varchar(255) not null,
        role varchar(255) check (role in ('ADMIN','USER')),
        primary key (id)
);

CREATE TABLE tasks (
        id BIGINT PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description VARCHAR(5000) NOT NULL,
        status VARCHAR(50) NOT NULL,
        task_priority VARCHAR(50) NOT NULL,
        author_id BIGINT NOT NULL,
        performer_id BIGINT NOT NULL,
        FOREIGN KEY (author_id) REFERENCES _users(id) ON DELETE CASCADE,
        FOREIGN KEY (performer_id) REFERENCES _users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
      comment_id BIGINT PRIMARY KEY,
      task_id BIGINT NOT NULL,
      commentator_id BIGINT NOT NULL,
      content VARCHAR(2500) NOT NULL,
      timestamp TIMESTAMP NOT NULL,
      FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
      FOREIGN KEY (commentator_id) REFERENCES _users(id) ON DELETE CASCADE
);