POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "root@mail.com",
  "password": "root",
  "role": "ADMIN"
}


###
POST http://localhost:64306/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "root@mail.com",
  "password": "root"
}

###
POST http://localhost:64306/api/v1/tasks
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290QG1haWwuY29tIiwiaWF0IjoxNzMyNzEwNTU2LCJleHAiOjE3MzI3OTY5NTZ9.Las5jOqFFNmkHygtqGHlFLwHCr09rcbNvU430MGxL0E

{
  "title": "Complete the project documentation",
  "description": "Ensure that all aspects of the project are documented thoroughly, including setup, features, and usage instructions.",
  "status": "IN_PROGRESS",
  "priority": "HIGH",
  "authorId": 1,
  "performerId": 1
}